#!/bin/sh

set -e -u

BVM_PATH=$(dirname $(realpath $0))

SERVICE_DIR=/usr/local/etc/sv

DEFAULT_BRIDGE=bridge0
DEFAULT_CORES=1
DEFAULT_IFMAC=none
DEFAULT_MEMORY=1024
DEFAULT_OS=freebsd

vm_root_fs=$(zfs get -H -o value,name bvm:active | awk '$1 == "on" { print $2 }' | head -n 1)

error ()
{
    echo "$@"
    exit 1
}

check_property ()
{
    [ "$1" = "bridge" ] && return 0
    [ "$1" = "cores"  ] && return 0
    [ "$1" = "ifmac"  ] && return 0
    [ "$1" = "memory" ] && return 0
    [ "$1" = "os"     ] && return 0

    error "Invalid property: $1."
}

perform_set ()
{
    local _vm_name="$1"
    local _property="$2"
    local _value="$3"

    local _vm_fs="${vm_root_fs}/${_vm_name}"

    check_property ${_property}

    zfs set bvm:${_property}=${_value} ${_vm_fs}
}

perform_create ()
{
    local _vm_name="$1"
    local _vm_fs="${vm_root_fs}/${_vm_name}"

    zfs create ${vm_root_fs}/${_vm_name}

    zfs set bvm:bridge=${DEFAULT_BRIDGE} ${_vm_fs}
    zfs set bvm:cores=${DEFAULT_CORES}   ${_vm_fs}
    zfs set bvm:ifmac=${DEFAULT_IFMAC}   ${_vm_fs}
    zfs set bvm:memory=${DEFAULT_MEMORY} ${_vm_fs}
    zfs set bvm:os=${DEFAULT_OS}         ${_vm_fs}
}

perform_destroy ()
{
    local _vm_name="$1"
    local _vm_fs="${vm_root_fs}/${_vm_name}"

    zfs destroy -rv ${_vm_fs}
}

perform_add_disk ()
{
    local _vm_name="$1"
    local _vm_fs="${vm_root_fs}/${_vm_name}"
    local _vol_size="$2"

    [ -n "${_vol_size}" ] || error "Invalid volume size: ${_vol_size}."

    local _index=0

    while true; do
        if [ -e /dev/zvol/${_vm_fs}/disk${_index} ]; then
            _index=$((${_index} + 1))
        else
            break
        fi
    done

    zfs create -b 4K -o volmode=dev -V ${_vol_size} -o compression=lz4 ${_vm_fs}/disk${_index}
}

perform_svinstall ()
{
    local _vm_name="$1"

    local _service=${SERVICE_DIR}/${_vm_name}

    mkdir -p ${_service}

    cat << EOF > ${_service}/run
#!/bin/sh
exec 2>&1
exec ${BVM_PATH}/bvm exec -n ${_vm_name} -s -x
EOF

    chmod 755 ${_service}/run

    mkdir -p ${_service}/log
    cat << EOF > ${_service}/log/run
#!/bin/sh

mkdir -p main
exec chpst svlogd -tt ./main

EOF

    chmod 755 ${_service}/log/run

    cat << EOF > ${_service}/finish
#!/bin/sh

exec 2>&1
exec ${BVM_PATH}/bvm finish -n ${_vm_name}
EOF

    chmod 755 ${_service}/finish
}

action="$1"

shift

perform_${action} "$@"

# zfs create -o canmount=off storage/vmm
# zfs set bvm:active=on storage/vmm
